import l from 'libs/langs/keys'

export default {
  // app shell labels
  // ======= CAUTION : Don't need to translate these language names =======
  [l.english]: 'English',
  [l.turkish]: 'Türkçe',
  [l.chinese]: '中文',
  [l.french]: 'Français',
  [l.arabic]: 'العربية',
  [l.signout]: 'خروج',
  // ============================= end caution ============================
  [l.capital_maps]: 'الخرائط',
  [l.capital_datasets]: 'البيانات',
  [l.capital_foundation]: 'المؤسسات',
  [l.capital_servers]: 'الخدمات',
  [l.capital_indices]: 'المؤشرات ',
  [l.capital_charts]: 'الرسوم البيانية',
  [l.capital_infrastructures]: 'البنية التحتية',
  [l.capital_search]: 'بحث ',

  [l.view_details]: 'عرض التفاصيل',
  [l.edit_map]: 'تحرير الخريطة ',
  [l.delete]: 'إلغاء',
  [l.set_layers_group]: 'تعيين مجموعة الطبقات',
  [l.set_theme]: 'تعيين النمط',
  [l.active_map]: 'خريطة مفعلة',
  [l.inactive_map]: 'خريطة غير مفعلة',
  [l.created]: 'إنشاء ',

  [l.extent]: 'امتداد',
  [l.enable_data_updates]: 'تمكين تحديثات البيانات مع الامتداد',
  [l.disable_data_updates]: 'تتعطيل تحديثات البيانات مع الامتداد',
  [l.select_theme]: 'اختيار النمط',
  [l.hide_live_trafic]: 'إخفاء حركة المرور ',
  [l.show_live_trafic]: 'إظهار حركة المرور',
  [l.clear_directions]: 'ازالة الاتجاهات',
  [l.base_layers]: 'الطبقة الاساسية ',
  [l.layers]: 'الطبقات ',
  [l.right_of_way]: 'تصريح ',

  [l.categories]: 'الفئات ',
  [l.all_visible]: 'اظهار الكل  ',
  [l.search_categories]: 'بحث الفئات ',
  [l.filter_categories]: 'تصفية الفئات حسب المدى الحالي ',
  [l.zoom_to_layer]: 'تكبير الطبقة ',
  [l.set_opacity]: 'ضبط التعتيم ',
  [l.set_visible]: 'ضبط الوضوح ',
  [l.line_segment]: 'خط القطعة ',
  [l.description]: 'الوصف ',
  [l.layer_name]: 'اسم الطبقة ',
  [l.feature_attribute]: 'سمة الميزة ',
  [l.map]: 'خريطة ',
  [l.server]: 'الخادم ',
  [l.wfs_name]: 'اسم خدمة ميزات الويب ',
  [l.wfs_uri]: ' معرف الموارد الموحد',
  [l.actions]: 'الاجراءات ',
  [l.see_layer_on_map]: 'انقر على الرمز لرؤية الطبقة على الخريطة ',
  [l.opacity]: 'التعتيم ',
  [l.visibility]: 'الوضوح ',
  [l.legend]: 'التفسير ',
  [l.no_legend_found]: 'لم يتم العثور على تفسير ',

  [l.map_details]: 'تفاصيل الخريطة ',
  [l.server_details]: 'تفاصيل الخادم ',
  [l.map_layers]: 'طبقات الخريطة ',
  [l.review]: 'مراجعة ',
  [l.name]: 'الاسم ',
  [l.crs]: 'نظام الترتيب الشامل',
  [l.min_zoom]: 'تكبير بسيط ',
  [l.max_zoom]: 'تكبير عالي ',
  [l.min_long]: 'اصغر خط طول ',
  [l.max_long]: 'اكبر خط طول ',
  [l.min_lat]: 'اصغر خط عرض ',
  [l.max_lat]: 'اكبر خط عرض ',
  [l.required_map_name]: ' الرجاء إدخال اسم الخريطة',
  [l.next]: 'التالي  ',
  [l.back]: 'رجوع ',
  [l.save]: 'حفظ ',
  [l.discard]: 'تجاهل ',

  [l.required_map_name]: 'الرجاء إدخال اسم الخريطة! ',
  [l.map_server_link]: 'حدد الخادم الذي تريد ربطه بخريطتك* ',
  [l.add_server]: 'أضف الخادم ',
  [l.server_name]: 'اسم الخادم ',
  [l.wms_URL]: 'WMS الرابط الاليكتروني ل',
  [l.wfs_URL]: 'WFS الرابط الاليكتروني ل',
  [l.no_servers_found]: 'لم يتم العثور على خوادم',
  [l.server_name]: 'اسم الخادم ',
  [l.required_server_name]: '!الرجاء إدخال اسم الخادم ',
  [l.required_WMS_URL]: ' WMS الرجاء ادخال الرابط الاليكتروني ل  ',
  [l.required_WFS_URL]: ' WFS الرجاء ادخال الرابط الاليكتروني ل ',
  [l.attributes]: 'السمات (ar)',
  [l.proxy_URL]: 'الرابط الاليكتروني للبروكسي ',
  [l.disable_server_warning]: 'هل تريد تعطيل هذا الخادم؟ ',
  [l.select_server_to_proceed]: 'يرجى تحديد الخادم للمتابعة ',
  [l.groups]: 'مجموعات ',
  [l.themes]: 'أنماط ',
  [l.retrieve_error]: 'تعذر استرداد البيانات',
  [l.layer_not_deleted]: 'الطبقة لم تحذف ',
  [l.layer_deleted_successfully]: 'تم حذف الطبقة بنجاح ',
  [l.something_went_wrong]: 'هناك خطأ ما ',
  [l.filter_by_server]: 'تصفية حسب الخادم ',
  [l.filter_by_map]: 'تصفية حسب الخريطة ',
  [l.reset]: 'اعادة تعيين ',
  [l.apply]: 'طلب',
  [l.map_layers]: 'طبقات الخريطة ',
  [l.search_layers]: 'بحث الطبقات ',
  [l.new_layer]: 'طبقة جديدة ',
  [l.edit]: 'تحرير ',
  [l.edit_and_duplicate]: 'تحرير وتكرار ',
  [l.delete_layer_msg]: 'هل أنت متأكد من حذف هذه الطبقة ',
  [l.label]: 'علامة ',
  [l.name]: 'اسم ',
  [l.featureType]: 'نوع الميزة ',
  [l.mapName]: 'اسم الخريطة ',
  [l.serverName]: 'اسم الخادم ',
  [l.actions]: 'الاجراءات ',
  [l.no_map_layers_found]: 'لم يتم العثور على طبقات خريطة ',
  [l.fetching_map_layers]: 'جلب طبقات الخريطة... ',
  [l.map_layer_groups]: 'مجموعات طبقة الخريطة ',
  [l.new_group]: 'مجموعة جديدة ',
  [l.deleting_group]: 'حذف المجموعة...',
  [l.group_deleted_succesfully]: 'تم حذف المجموعة بنجاح ',
  [l.group_not_deleted]: 'المجموعة لم محذوفة ',
  [l.delete_group_msg]: 'هل أنت متأكد من حذف هذه المجموعة ? ',
  [l.fetching_map_layer_groups]: 'جلب مجموعات طبقة الخريطة... ',
  [l.no_map_layer_groups_found]: 'لم يتم العثور على مجموعات طبقة الخريطة ',
  [l.map_themes]: 'نمط الخريطة ',
  [l.new_theme]: 'نمط جديد ',
  [l.deleting_theme]: 'حذف النمط... ',
  [l.theme_deleted_succesfully]: 'تم حذف النمط بنجاح ',
  [l.theme_not_deleted]: 'النمط لم يحذف ',
  [l.delete_theme_msg]: ' هل أنت متأكد من حذف هذا االنمط؟  ',
  [l.fetching_map_themes]: 'جلب انماط الخريطة... ',
  [l.no_map_themes_found]: 'لم يتم العثور على نمط الخريطة ',
  [l.filter_layers]: 'تصفية الطبقات ',
  [l.fetching_info]: 'إحضار المعلومات... ',
  [l.saving_layer]: 'جاري حفظ الطبقة... ',
  [l.layer_saved_successfully]: 'تم حفظ الطبقة بنجاح ',
  [l.error_ocurred_while_fetching_layer]: 'حدث خطأ أثناء جلب الطبقة (ar)',

  [l.upload_dxf_file]: 'dxfتحميل ملف ',
  [l.upload_kroki]: 'تحميل الكروكي ',
  [l.draw_on_map]: 'ارسم على الخريطة ',
  [l.input_coordinate]: 'ادخال الاحداثيات',
  [l.upload_image]: 'تحميل صورة ',
  [l.upload_file]: 'تحميل ملف ',
  [l.areas_details]: 'تفاصيل المناطق ',
  [l.delete_area]: 'حذف المنطقة ',
  [l.show_area_on_map]: 'إظهار المنطقة على الخريطة ',
  [l.coordinate_system]: 'نظام الإحداثيات ',
  [l.northing]: 'شمال ',
  [l.easting]: 'شرق ',
  [l.actions]: 'اجراءات ',
  [l.no_data]: 'لا يوجد بيانات ',
  [l.add_new_coordinate]: 'إضافة احداثيات جديدة ',
  [l.edit]: 'تعديل',
  [l.delete]: 'إلغاء',
  [l.yes]: 'نعم',
  [l.no]: 'لا',
  [l.validate]: 'التحقق ',
  [l.validating_areas_details]: 'التحقق منن تفاصيل المناطق ',
  [l.validation_results]: 'نتائج التحقق',
  [l.result_options]: 'خيارات النتائج ',
  [l.approved]: 'موافقة ',
  [l.export_results]: 'استخراج النتائج ',
  [l.select_file]: ' اختيار ملف ',
  [l.select_image]: 'اختيار صورة ',
  [l.layer_icon_here]: 'ادراج رمز الطبقة هنا ',
  [l.dxf_file_here]: 'هنا dxf إدراج ملف ',
  [l.kroki_image_here]: '    ادراج صورة الكروكي هنا ',
  [l.select_coord_system]: 'حدد نظام الاحداثيات ',
  [l.draw_shape_on_map]: ' !الرجاء رسم الشكل على الخريطة الآن',
  [l.reupload_image]: 'تحميل الصورة ',

  [l.right_of_way]: 'تصريح ',
  [l.land_investment]: 'استثمار ارض ',
  [l.nursery_permit]: 'تصريح حضانة ',
  [l.search_area]: 'بحث منطقة ',
  [l.loading_info]: 'معلومات التحميل ... ',
  [l.loading_layer_data]: 'تحميل بيانات الطبقة... ',
  [l.input_area_details]: 'الرجاء إدخال تفاصيل المنطقة! ',
  [l.loading_map]: 'تحميل الخريطة ',
  [l.loading_app]: 'تحميل التطبيق ',

  [l.select_map_layers]: 'تحديد طبقات الخريطة* ',
  [l.search_layers]: 'بحث الطبقات',
  [l.server_name]: 'اسم الخادم ',
  [l.select_all]: 'إختيار الكل',
  [l.select_all]: 'إختيار الكل ',
  [l.select_base_layers]: 'تحديد الطبقة الاساسية* ',
  [l.no_base_layers_found]: 'لم يتم العثور على طبقات أساسية ',
  [l.base_layer_name]: 'اسم الطبقة الاساسية ',
  [l.layer_type]: 'نوع الطبقة ',
  [l.url]: 'الرابط الالكتروني ',

  [l.public]: 'عام ',
  [l.anyone_can_see_map]: 'الكل يشاهد الخريطة ',
  [l.invite_only]: 'دعوة فقط ',
  [l.only_members_can_see_map]: 'الاعظاء فقط من يشاهد الخريطة ',
  [l.set_bounds]: 'تعيين الحدود ',
  [l.share_map_with]: 'مشاركة الخريطة بـ ',
  [l.share_via_email]: 'مشاركة عبر البريد الالكتروني ',
  [l.email]: 'بريد اليكتروني',
  [l.publish]: 'نشر ',
  [l.step]: 'خطوة',

  [l.no_area_found]: 'لم يتم العثور على منطقة ',
  [l.area_radius]: 'نصف قطر المنطقة',
  [l.gis_product]: 'منتج نظام المعلومات الجغرافية',
  [l.select_workspaces]: 'اختيار مساحة العمل ',
  [l.create_map]: 'إنشاء خريطة',
  [l.view_dashboard]: 'عرض المؤشرات البيانية ',
  [l.map_image_here]: 'ادراج صورة الخريطة او  ',
  [l.map_image]: 'صورة الخريطة ',
  [l.save_exit]: 'حفظ وخروج ',
  [l.map_builder]: 'منشئ الخرائط ',
  [l.layers_order]: 'ترتيب الطبقات ',
  [l.no_layer_found]: 'لا توجد طبقة ',
  [l.discard_changes]: 'سيتم تجاهل التغييرات الحالية !',
  [l.intersection]: 'تداخل ',
  [l.fetching_maps]: 'جلب الخريطة',
  [l.default_theme]: 'إفتراضي النمط',
  [l.reupload_file]: 'تحميل ملف',
  [l.area]: 'المنطقة',
  [l.buildings]: 'البنايات',
  [l.schools]: 'المدارس',
  [l.hospitals]: 'المستشفيات',
  [l.pipelines]: 'خطوط الأنابيب',
  [l.intrastructure]: 'البنية التحتية',
  [l.population]: 'تعداد السكان',
  [l.studio]: 'Studio',
  [l.inf_description]:
    'تتكون البنية التحتية من الهياكل المادية العامة والخاصة مثل الطرق والسكك الحديدية والجسور والأنفاق وإمدادات المياه والصرف الصحي والشبكات الكهربائية والاتصالات (بما في ذلك الاتصال بالإنترنت والوصول إلى النطاق العريض)',
  [l.view_in_3d]: 'عرض ثلاثي الأبعاد',
  [l.change_radius]: 'تغيير نصف القطر',
}
