import l from 'libs/langs/keys'

export default {
  // app shell labels
  // ======= CAUTION : Don't need to translate these language names =======
  [l.english]: 'English',
  [l.turkish]: 'Türkçe',
  [l.chinese]: '中文',
  [l.french]: 'Français',
  [l.arabic]: 'العربية',
  [l.signout]: 'Sign out',
  // ============================= end caution ============================
  [l.capital_maps]: 'MAPS',
  [l.capital_datasets]: 'DATASETS',
  [l.capital_foundation]: 'FOUNDATIONS',
  [l.capital_servers]: 'SERVERS',
  [l.capital_indices]: 'INDICES',
  [l.capital_charts]: 'CHARTS',
  [l.capital_infrastructures]: 'INFRASTRUCTURES',
  [l.capital_search]: 'SEARCH',

  [l.view_details]: 'View Details',
  [l.edit_map]: 'Edit Map',
  [l.delete]: 'Delete',
  [l.set_layers_group]: 'Set Layers Group',
  [l.set_theme]: 'Set Theme',
  [l.active_map]: 'Active Map',
  [l.inactive_map]: 'Inactive Map',
  [l.created]: 'Created:',

  [l.extent]: 'Extent',
  [l.enable_data_updates]: 'Enable Data Updates With Extent',
  [l.disable_data_updates]: 'Disable Data Updates With Extent',
  [l.select_theme]: 'Select Theme',
  [l.hide_live_trafic]: 'Hide Live Trafic',
  [l.show_live_trafic]: 'Show Live Trafic',
  [l.clear_directions]: 'Clear Directions',
  [l.base_layers]: 'Base Layers',
  [l.layers]: 'Layers',
  [l.right_of_way]: 'Right Of Way',

  [l.categories]: 'Categories',
  [l.all_visible]: 'All visible',
  [l.search_categories]: 'Search Categories',
  [l.filter_categories]: 'Filter Categories by Current Extent',
  [l.zoom_to_layer]: 'Zoom to Layer',
  [l.set_opacity]: 'Set Opacity',
  [l.set_visible]: 'Set Visible',
  [l.line_segment]: 'Line Segment',
  [l.description]: 'Description',
  [l.layer_name]: 'Layer Name',
  [l.feature_attribute]: 'Feature Attribute',
  [l.map]: 'Map',
  [l.server]: 'Server',
  [l.wfs_name]: 'WFS Name',
  [l.wfs_uri]: 'WFS URI',
  [l.actions]: 'Actions',
  [l.see_layer_on_map]: 'Click on icon to see layer on map',
  [l.opacity]: 'Opacity',
  [l.visibility]: 'Visibility',
  [l.legend]: 'Legend',
  [l.no_legend_found]: 'NO LEGEND FOUND',

  [l.map_details]: 'Map Details',
  [l.server_details]: 'Server Details',
  [l.map_layers]: 'Map Layers',
  [l.review]: 'Review',
  [l.name]: 'Name',
  [l.crs]: 'CRS',
  [l.min_zoom]: 'Min Zoom',
  [l.max_zoom]: 'Max Zoom',
  [l.min_long]: 'Min Lon',
  [l.max_long]: 'Max Lon',
  [l.min_lat]: 'Min Lat',
  [l.max_lat]: 'Max Lat',
  [l.required_map_name]: 'Please input name of map!',
  [l.next]: 'Next',
  [l.back]: 'Back',
  [l.save]: 'Save',
  [l.discard]: 'Discard',

  [l.required_map_name]: 'Please input name of map!',
  [l.map_server_link]: 'Select Server which you want to link with your map*',
  [l.add_server]: 'Add Server',
  [l.server_name]: 'Server Name',
  [l.wms_URL]: 'WMS URL',
  [l.wfs_URL]: 'WFS URL',
  [l.no_servers_found]: 'No Servers Found',
  [l.server_name]: 'Server Name',
  [l.required_server_name]: 'Please input the name of server!',
  [l.required_WMS_URL]: 'Please input WMS URL!',
  [l.required_WFS_URL]: 'Please input WFS URL!',
  [l.attributes]: 'Attributes',
  [l.proxy_URL]: 'Proxy URL',
  [l.disable_server_warning]: 'Do you want to disable this server?',
  [l.select_server_to_proceed]: 'Please Select Server to Proceed',
  [l.groups]: 'Groups',
  [l.themes]: 'Themes',
  [l.retrieve_error]: 'Unable to retrive data',
  [l.layer_not_deleted]: 'Layer Not Deleted',
  [l.layer_deleted_successfully]: 'Layer Deleted Sucessfully',
  [l.something_went_wrong]: 'Something Went Wrong',
  [l.filter_by_server]: 'Filter By Server',
  [l.filter_by_map]: 'Filter By Map',
  [l.reset]: 'Reset',
  [l.apply]: 'Apply',
  [l.map_layers]: 'Map Layers',
  [l.search_layers]: 'Search Layers',
  [l.new_layer]: 'New Layer',
  [l.edit]: 'Edit',
  [l.edit_and_duplicate]: 'Edit & Duplicate',
  [l.delete_layer_msg]: 'Are you sure to delete this layer',
  [l.label]: 'label',
  [l.name]: 'Name',
  [l.featureType]: 'Feature Type',
  [l.mapName]: 'Map Name',
  [l.serverName]: 'Server Name',
  [l.actions]: 'Actions',
  [l.no_map_layers_found]: 'No Map Layers Found',
  [l.fetching_map_layers]: 'Fetching Map Layers...',
  [l.map_layer_groups]: 'Map Layer Groups',
  [l.new_group]: 'New Group',
  [l.deleting_group]: 'Deleting Group...',
  [l.group_deleted_succesfully]: 'Group Deleted Sucessfully',
  [l.group_not_deleted]: 'Group Not Deleted',
  [l.delete_group_msg]: 'Are you sure to delete this group ?',
  [l.fetching_map_layer_groups]: 'Fetching Map Layer Groups...',
  [l.no_map_layer_groups_found]: 'No Map Layer Groups Found',
  [l.map_themes]: 'Map Themes',
  [l.new_theme]: 'New Theme',
  [l.deleting_theme]: 'Deleting Theme...',
  [l.theme_deleted_succesfully]: 'Theme Deleted Sucessfully',
  [l.theme_not_deleted]: 'Theme Not Deleted',
  [l.delete_theme_msg]: 'Are you sure to delete this theme ?',
  [l.fetching_map_themes]: 'Fetching Map Themes...',
  [l.no_map_themes_found]: 'No Map Themes Found',
  [l.filter_layers]: 'Filter Layers',
  [l.fetching_info]: 'Fetching Info...',
  [l.saving_layer]: 'Saving Layer...',
  [l.layer_saved_successfully]: 'Layer Saved Successfully',
  [l.error_ocurred_while_fetching_layer]: 'Error ocuured while fetching layer',

  [l.upload_dxf_file]: 'Upload DXF File',
  [l.upload_kroki]: 'Upload Kroki',
  [l.draw_on_map]: 'Draw on Map',
  [l.input_coordinate]: 'Input Coordinate',
  [l.upload_image]: 'Upload Image',
  [l.upload_file]: 'Upload File',
  [l.areas_details]: 'Areas Details',
  [l.delete_area]: 'Delete Area',
  [l.show_area_on_map]: 'Show Area On Map',
  [l.coordinate_system]: 'Coordiante System',
  [l.northing]: 'Northing',
  [l.easting]: 'Easting',
  [l.actions]: 'Actions',
  [l.no_data]: 'No Data',
  [l.add_new_coordinate]: 'Add New Coordinate',
  [l.edit]: 'Edit',
  [l.delete]: 'Delete',
  [l.yes]: 'Yes',
  [l.no]: 'No',
  [l.validate]: 'Validate',
  [l.validating_areas_details]: 'Validating Areas Details',
  [l.validation_results]: 'Validation Results',
  [l.result_options]: 'Result Options',
  [l.approved]: 'Approved',
  [l.export_results]: 'Export Results',
  [l.select_file]: 'Select File',
  [l.select_image]: 'Select Image',
  [l.layer_icon_here]: 'Drag & Drop layer icon here or',
  [l.dxf_file_here]: 'Drag & Drop dxf file here or',
  [l.kroki_image_here]: 'Drag & Drop kroki image here or',
  [l.select_coord_system]: 'Select Coordinate System',
  [l.draw_shape_on_map]: 'Please draw shape on map now!',
  [l.reupload_image]: 'Reupload Image',
  [l.reupload_file]: 'Reupload File',

  [l.right_of_way]: 'Right Of Way',
  [l.land_investment]: 'Land Investment',
  [l.nursery_permit]: 'Nursery Permit',
  [l.search_area]: 'Search Area',

  [l.no_area_found]: 'No Area Found',
  [l.loading_info]: 'Loading Info ...',
  [l.loading_layer_data]: 'Loading Layer Data  ...',
  [l.input_area_details]: 'Please Enter Area Details!',
  [l.loading_map]: 'Loading Map ...',
  [l.loading_app]: 'Loading App ...',
  [l.select_map_layers]: 'Select Map Layers*',
  [l.search_layers]: 'Search Layers',
  [l.server_name]: 'Server Name',
  [l.select_all]: 'Select All',
  [l.select_base_layers]: 'Select Base Layers*',
  [l.no_base_layers_found]: 'No Base Layers Found',
  [l.base_layer_name]: 'Base Layer Name',
  [l.layer_type]: 'Layer Type',
  [l.url]: 'URL',

  [l.public]: 'Public',
  [l.anyone_can_see_map]: 'Anyone can see map',
  [l.invite_only]: 'Invite Only',
  [l.only_members_can_see_map]: 'Only members can see map',

  [l.set_bounds]: 'Set Bounds',
  [l.share_map_with]: 'Share Map with',
  [l.share_via_email]: 'Share via Email',
  [l.email]: 'Email',
  [l.publish]: 'Publish',
  [l.step]: 'Step',
  [l.area_radius]: 'Area Radius',
  [l.gis_product]: 'GIS Product',
  [l.studio]: 'Studio',
  [l.select_workspaces]: 'Select Workspaces',
  [l.create_map]: 'Create Map',
  [l.view_dashboard]: 'View Dashboard',

  /// //////////////////////////////////////////////////////

  [l.map_image_here]: 'Drag & Drop map image here or',
  [l.map_image]: 'Map Image',
  [l.save_exit]: 'Save & Exit',
  [l.map_builder]: 'Map Builder',
  [l.layers_order]: 'Layers Order',
  [l.no_layer_found]: 'No Layer Found',
  [l.discard_changes]: 'Your current changes will be discarded!',
  [l.intersection]: 'Intersection',
  [l.fetching_maps]: 'Fetching Maps ...',
  [l.default_theme]: 'Default Theme',
  [l.reupload_file]: 'Reupload File',
  [l.area]: 'Area',
  [l.buildings]: 'Buildings',
  [l.schools]: 'Schools',
  [l.hospitals]: 'Hospitals',
  [l.pipelines]: 'Pipelines',
  [l.intrastructure]: 'Intrastructure',
  [l.population]: 'Population',
  [l.inf_description]:
    'Infrastructure is composed of public and private physical structures such as roads, railways, bridges, tunnels, water supply, sewers, electrical grids, and telecommunications (including Internet connectivity and broadband access)',
  [l.view_in_3d]: 'View in 3d',
  [l.change_radius]: 'Change radius',
}
