import i18n from 'i18n-js'
import l from 'libs/langs/keys'

export const modules = [
  {
    key: 'workspaces',
    label: 'WORKSPACES',
    iconClassName: 'mdi mdi-cards-variant',
    path: '/ams/inventory',
    submodules: [
      {
        key: 'base',
        iconClassName: 'mdi-webpack',
        disabled: true,
        path: '/ams/inventory/base',
      },
      {
        key: 'consumption',
        iconClassName: 'mdi-webpack',
        path: '/ams/inventory/consumption',
      },
      {
        key: 'surplus',
        iconClassName: 'mdi-webpack',
        path: '/ams/inventory/surplus',
      },
      {
        key: 'transfer',
        iconClassName: 'mdi-webpack',
        path: '/ams/inventory/transfer',
      },
      {
        key: 'disposal',
        iconClassName: 'mdi-webpack',
        path: '/ams/inventory/disposal',
      },
    ],
  },
  {
    key: 'search_filter',
    label: `${i18n.t(l.find_filter)}`,
    iconClassName: 'mdi mdi-file',
    path: '/trove/search',
    submodules: [],
  },
  {
    key: 'files',
    label: 'FILES',
    iconClassName: 'mdi mdi-file',
    path: '/ams/reserves',
    submodules: [
      {
        key: 'load',
        iconClassName: 'mdi-webpack',
        path: '/ams/reserves/load',
      },
    ],
  },
  {
    key: 'dashboards',
    label: 'DASHBOARDS',
    iconClassName: 'mdi mdi-view-dashboard',
    submodules: [
      {
        key: 'wpb',
        disabled: true,

        iconClassName: 'mdi-webpack',
        path: '/ams/planning/wpb',
      },
      {
        key: 'fyp',
        iconClassName: 'mdi-webpack',
        path: '/ams/planning/fyp',
      },
    ],
  },

  {
    key: 'tasks',
    label: 'TASKS',
    iconClassName: 'mdi mdi-file-document',
    path: '/ams/permit',
    submodules: [
      {
        key: 'drill',
        // iconClassName: "mdi-webpack",
        path: '/ams/permit/drill',
        iconClassName: 'mdi-webpack',
      },
      {
        key: 'suspend',
        iconClassName: 'mdi-webpack',
        path: '/ams/permit/suspend',
      },
      {
        key: 'abandon',
        iconClassName: 'mdi-webpack',
        path: '/ams/permit/abandon',
      },
    ],
  },
  {
    key: 'meetings',
    label: 'MEETINGS',
    iconClassName: 'mdi mdi-account-network',
    path: '/ams/production',
    submodules: [
      {
        key: 'daily',
        iconClassName: 'mdi-webpack',
        path: '/ams/production/daily',
      },
      {
        key: 'monthly',
        iconClassName: 'mdi-webpack',
        path: '/ams/production/monthly',
      },
    ],
  },
  {
    key: 'planners',
    label: 'PLANNERS',
    iconClassName: 'mdi mdi-calendar-range',
    path: '/ams/icv',
    submodules: [
      {
        key: 'load',
        iconClassName: 'mdi-webpack',
        path: '/ams/icv/load',
      },
      {
        key: 'statistical',
        iconClassName: 'mdi-webpack',
        path: '/ams/icv/statistical',
      },
    ],
  },
  {
    key: 'data',
    label: 'DATA',
    iconClassName: 'mdi mdi-database',
    path: '/ams/data',
    submodules: [],
  },
]

export const navModules = [
  {
    key: 'trove',
    label: 'Trove',
    path: '/',
    iconClassName: 'mdi mdi-cards-variant',
    submodules: [],
  },
  {
    key: 'configurator',
    label: 'Configurator',
    // eslint-disable-next-line no-undef
    path: `${PRODUCT_APP_URL_STUDIO}`,
    iconClassName: 'mdi mdi-cards-variant',
    submodules: [],
  },
]

export const fixedModules = [
  {
    key: 'analytics',
    iconClassName: 'mdi-chart-areaspline',
    submodules: [
      {
        key: 'dashboard',
        name: 'Dashboard',
        iconClassName: 'mdi mdi-view-dashboard',
      },
      {
        key: 'bi',
        name: 'Business Int.',
        iconClassName: 'mdi mdi-google-analytics',
      },
      {
        key: 'map',
        name: 'Map',
        iconClassName: 'mdi mdi-google-maps',
      },
      {
        key: 'list',
        name: 'List',
        iconClassName: 'mdi mdi-format-list-bulleted',
      },
    ],
  },
]

export const GEOSERVER_URL =
  process.env.GEOSERVER_URL || 'https://geo.target.meeraspace.com'

export const geoserverURLS = {
  wmsgeoserver: '/geoserver/rkms/wms?',
  geoserver: '/geoserver/rkms/wfs',
}
export const mapLayers = [
  {
    LAYERNAME: 'Governorate',
    URL: geoserverURLS.wmsgeoserver,
    LAYERS: 'rkms:Governorate',
    TILED: true,
    FORMAT: 'image/png8',
    CRS: 'EPSG:3857',
    VISIBLE: false,
    LAYERTYPE: 'wms',
    SERVERTYPE: 'geoserver',
    LAYEROPACITY: 0.75,
    LAYERORDER: '0',
  },
  {
    LAYERNAME: 'Wells',
    URL: geoserverURLS.wmsgeoserver,
    LAYERS: 'rkms:ldr_wells',
    TILED: true,
    FORMAT: 'image/png8',
    CRS: 'EPSG:3857',
    VISIBLE: false,
    LAYERTYPE: 'wms',
    SERVERTYPE: 'geoserver',
    LAYEROPACITY: 100,
    LAYERORDER: '0',
  },
  {
    LAYERNAME: 'Active Blocks',
    URL: geoserverURLS.wmsgeoserver,
    LAYERS: 'rkms:active_blocks',
    TILED: true,
    FORMAT: 'image/png8',
    CRS: 'EPSG:3857',
    VISIBLE: false,
    LAYERTYPE: 'wms',
    SERVERTYPE: 'geoserver',
    LAYEROPACITY: 100,
    LAYERORDER: '0',
  },
  {
    LAYERNAME: 'AMS permit',
    URL: GEOSERVER_URL + geoserverURLS.wmsgeoserver,
    LAYERS: 'rkms:nz_permit_2193_ams',
    TILED: true,
    FORMAT: 'image/png8',
    CRS: 'EPSG:2193',
    VISIBLE: false,
    LAYERTYPE: 'wms',
    SERVERTYPE: 'geoserver',
    LAYEROPACITY: 100,
    LAYERORDER: '0',
  },
  {
    LAYERNAME: 'Hammamet Concessions',
    URL: GEOSERVER_URL + geoserverURLS.wmsgeoserver,
    LAYERS: 'rkms:gulf_of_hammamet_concessions',
    TILED: true,
    FORMAT: 'image/png8',
    CRS: 'EPSG:4326',
    VISIBLE: false,
    LAYERTYPE: 'wms',
    SERVERTYPE: 'geoserver',
    LAYEROPACITY: 100,
    LAYERORDER: '0',
  },
  {
    LAYERNAME: 'Hammamet Open Blocks',
    URL: GEOSERVER_URL + geoserverURLS.wmsgeoserver,
    LAYERS: 'rkms:gulf_of_hammamet_open_blocks',
    TILED: true,
    FORMAT: 'image/png8',
    CRS: 'EPSG:4326',
    VISIBLE: false,
    LAYERTYPE: 'wms',
    SERVERTYPE: 'geoserver',
    LAYEROPACITY: 100,
    LAYERORDER: '0',
  },
  {
    LAYERNAME: 'Hammamet Permits',
    URL: GEOSERVER_URL + geoserverURLS.wmsgeoserver,
    LAYERS: 'rkms:gulf_of_hammamet_permits',
    TILED: true,
    FORMAT: 'image/png8',
    CRS: 'EPSG:4326',
    VISIBLE: false,
    LAYERTYPE: 'wms',
    SERVERTYPE: 'geoserver',
    LAYEROPACITY: 100,
    LAYERORDER: '0',
  },
  {
    LAYERNAME: 'Blue Book Basins',
    URL: GEOSERVER_URL + geoserverURLS.wmsgeoserver,
    LAYERS: 'rkms:blue_book_basins',
    TILED: true,
    FORMAT: 'image/png8',
    CRS: 'EPSG:2193',
    VISIBLE: false,
    LAYERTYPE: 'wms',
    SERVERTYPE: 'geoserver',
    LAYEROPACITY: 100,
    LAYERORDER: '0',
  },
  {
    LAYERNAME: 'Bathymetry',
    URL: GEOSERVER_URL + geoserverURLS.wmsgeoserver,
    LAYERS: 'rkms:niwa_nz_bathymetry',
    TILED: true,
    FORMAT: 'image/png8',
    CRS: 'EPSG:3857',
    VISIBLE: false,
    LAYERTYPE: 'wms',
    SERVERTYPE: 'geoserver',
    LAYEROPACITY: 100,
    LAYERORDER: '0',
  },
  {
    LAYERNAME: 'NZ EEZ',
    URL: GEOSERVER_URL + geoserverURLS.wmsgeoserver,
    LAYERS: 'rkms:nz_eez',
    TILED: true,
    FORMAT: 'image/png8',
    CRS: 'EPSG:3857',
    VISIBLE: false,
    LAYERTYPE: 'wms',
    SERVERTYPE: 'geoserver',
    LAYEROPACITY: 100,
    LAYERORDER: '0',
  },
  {
    LAYERNAME: 'Permit',
    URL: GEOSERVER_URL + geoserverURLS.wmsgeoserver,
    LAYERS: 'rkms:nz_permit_2193',
    TILED: true,
    FORMAT: 'image/png8',
    CRS: 'EPSG:2193',
    VISIBLE: false,
    LAYERTYPE: 'wms',
    SERVERTYPE: 'geoserver',
    LAYEROPACITY: 100,
    LAYERORDER: '0',
  },
  {
    LAYERNAME: 'Geological Units',
    URL: GEOSERVER_URL + geoserverURLS.wmsgeoserver,
    LAYERS: 'rkms:nzl_gns_250k_geological_units',
    TILED: true,
    FORMAT: 'image/png8',
    CRS: 'EPSG:3857',
    VISIBLE: false,
    LAYERTYPE: 'wms',
    SERVERTYPE: 'geoserver',
    LAYEROPACITY: 100,
    LAYERORDER: '0',
  },
  {
    LAYERNAME: 'Petroleum Fields',
    URL: GEOSERVER_URL + geoserverURLS.wmsgeoserver,
    LAYERS: 'rkms:petroleum_fields',
    TILED: true,
    FORMAT: 'image/png8',
    CRS: 'EPSG:3857',
    VISIBLE: false,
    LAYERTYPE: 'wms',
    SERVERTYPE: 'geoserver',
    LAYEROPACITY: 100,
    LAYERORDER: '0',
  },
  {
    LAYERNAME: 'Project Outline',
    URL: GEOSERVER_URL + geoserverURLS.wmsgeoserver,
    LAYERS: 'rkms:ppdmProject_outline',
    TILED: true,
    FORMAT: 'image/png8',
    CRS: 'EPSG:3857',
    VISIBLE: false,
    LAYERTYPE: 'wms',
    SERVERTYPE: 'geoserver',
    LAYEROPACITY: 100,
    LAYERORDER: '0',
  },
  {
    LAYERNAME: 'Fields',
    URL: GEOSERVER_URL + geoserverURLS.wmsgeoserver,
    LAYERS: 'rkms:fields',
    TILED: true,
    FORMAT: 'image/png8',
    CRS: 'EPSG:3857',
    VISIBLE: false,
    LAYERTYPE: 'wms',
    SERVERTYPE: 'geoserver',
    LAYEROPACITY: 100,
    LAYERORDER: '0',
  },
]

export const maplayersSeismicWell = {
  SeismicSchema: [
    {
      LAYERNAME: 'Seismic 2D',
      URL: GEOSERVER_URL + geoserverURLS.wmsgeoserver,
      LAYERS: 'rkms:ppdmproject_seismic2d',
      TILED: true,
      FORMAT: 'image/png8',
      CRS: 'EPSG:3857',
      VISIBLE: true,
      LAYERTYPE: 'wms',
      SERVERTYPE: 'geoserver',
      LAYEROPACITY: 100,
      LAYERORDER: '0',
    },
    {
      LAYERNAME: 'Seismic 3D',
      URL: GEOSERVER_URL + geoserverURLS.wmsgeoserver,
      LAYERS: 'rkms:ppdmproject_seismic3d',
      TILED: true,
      FORMAT: 'image/png8',
      CRS: 'EPSG:3857',
      VISIBLE: true,
      LAYERTYPE: 'wms',
      SERVERTYPE: 'geoserver',
      LAYEROPACITY: 100,
      LAYERORDER: '0',
    },
  ],
  WellSchema: [
    {
      LAYERNAME: 'Wellbore',
      URL: GEOSERVER_URL + geoserverURLS.wmsgeoserver,
      LAYERS: 'rkms:ppdmProject_well',
      TILED: true,
      FORMAT: 'image/png8',
      CRS: 'EPSG:4326',
      VISIBLE: true,
      LAYERTYPE: 'wms',
      SERVERTYPE: 'geoserver',
      LAYEROPACITY: 100,
      LAYERORDER: '0',
    },
  ],
}

export const regionalMapLayers = [
  {
    LAYERNAME: 'Blue Book Basins',
    URL: geoserverURLS.wmsgeoserver,
    LAYERS: 'rkms:blue_book_basins',
    TILED: true,
    FORMAT: 'image/png8',
    CRS: 'EPSG:3857',
    VISIBLE: false,
    LAYERTYPE: 'wms',
    SERVERTYPE: 'geoserver',
    LAYEROPACITY: 0.75,
    LAYERORDER: '0',
  },
  {
    LAYERNAME: 'NZ EEZ',
    URL: geoserverURLS.wmsgeoserver,
    LAYERS: 'rkms:nz_eez',
    TILED: true,
    FORMAT: 'image/png8',
    CRS: 'EPSG:3857',
    VISIBLE: false,
    LAYERTYPE: 'wms',
    SERVERTYPE: 'geoserver',
    LAYEROPACITY: 0.75,
    LAYERORDER: '0',
  },
  {
    LAYERNAME: 'Bathymetry',
    URL: geoserverURLS.wmsgeoserver,
    LAYERS: 'rkms:niwa_nz_bathymetry',
    TILED: true,
    FORMAT: 'image/png8',
    CRS: 'EPSG:3857',
    VISIBLE: false,
    LAYERTYPE: 'wms',
    SERVERTYPE: 'geoserver',
    LAYEROPACITY: 0.75,
    LAYERORDER: '0',
  },
  {
    LAYERNAME: 'Geological Units',
    URL: geoserverURLS.wmsgeoserver,
    LAYERS: 'rkms:nzl_gns_250k_geological_units',
    TILED: true,
    FORMAT: 'image/png8',
    CRS: 'EPSG:3857',
    VISIBLE: false,
    LAYERTYPE: 'wms',
    SERVERTYPE: 'geoserver',
    LAYEROPACITY: 0.75,
    LAYERORDER: '0',
  },
  {
    LAYERNAME: 'NZ Permit',
    URL: geoserverURLS.wmsgeoserver,
    LAYERS: 'rkms:nz_permit_2193',
    TILED: true,
    FORMAT: 'image/png8',
    CRS: 'EPSG:3857',
    VISIBLE: false,
    LAYERTYPE: 'wms',
    SERVERTYPE: 'geoserver',
    LAYEROPACITY: 0.75,
    LAYERORDER: '0',
  },
  {
    LAYERNAME: 'Fields',
    URL: geoserverURLS.wmsgeoserver,
    LAYERS: 'rkms:petroleum_fields',
    TILED: true,
    FORMAT: 'image/png8',
    CRS: 'EPSG:3857',
    VISIBLE: false,
    LAYERTYPE: 'wms',
    SERVERTYPE: 'geoserver',
    LAYEROPACITY: 0.75,
    LAYERORDER: '0',
  },
  {
    LAYERNAME: 'Pipe Lines',
    URL: geoserverURLS.wmsgeoserver,
    LAYERS: 'filespace:PipeLines',
    TILED: true,
    FORMAT: 'image/png8',
    CRS: 'EPSG:3857',
    VISIBLE: false,
    LAYERTYPE: 'wms',
    SERVERTYPE: 'geoserver',
    LAYEROPACITY: 0.75,
    LAYERORDER: '0',
  },
  {
    LAYERNAME: 'Power Lines',
    URL: geoserverURLS.wmsgeoserver,
    LAYERS: 'filespace:PowerLinesFinal',
    TILED: true,
    FORMAT: 'image/png8',
    CRS: 'EPSG:3857',
    VISIBLE: false,
    LAYERTYPE: 'wms',
    SERVERTYPE: 'geoserver',
    LAYEROPACITY: 0.75,
    LAYERORDER: '0',
  },
  {
    LAYERNAME: 'Concession',
    URL: geoserverURLS.wmsgeoserver,
    LAYERS: 'rkms:bo_concession',
    TILED: true,
    FORMAT: 'image/png8',
    CRS: 'EPSG:3857',
    VISIBLE: false,
    LAYERTYPE: 'wms',
    SERVERTYPE: 'geoserver',
    LAYEROPACITY: 0.75,
    LAYERORDER: '0',
  },
]

export const newzealandMapExtent = {
  YMIN: -30.704646673364607,
  XMIN: 140.2659891952507,
  YMAX: -57.24970783361135,
  XMAX: 200.95446575775068,
}

export const defaultColors = [
  {
    id: 'red',
    color: '#f44336',
  },
  {
    id: 'pink',
    color: '#e91e63',
  },
  {
    id: 'purple',
    color: '#9c2760',
  },
  {
    id: 'royal_blue',
    color: '#673ab7',
  },
  {
    id: 'blue',
    color: '#3f51b5',
  },
  {
    id: 'light_blue',
    color: '#2196f3',
  },
  {
    id: 'green_blue',
    color: '#00bcd4',
  },
  {
    id: 'sea_green',
    color: '#009688',
  },
  {
    id: 'green',
    color: '#00a759',
  },
  {
    id: 'lime',
    color: '#8bc34a',
  },
  {
    id: 'yellow',
    color: '#ffc107',
  },
  {
    id: 'orange',
    color: '#ff9800',
  },
  {
    id: 'brown',
    color: '#795548',
  },
  {
    id: 'grey',
    color: '#607d8b',
  },
]

export const languages = [
  {
    key: 'en',
    name: i18n.t(l.english),
    label: i18n.t(l.english),
    active: true,
  },
  {
    key: 'tr',
    name: i18n.t(l.turkish),
    label: i18n.t(l.turkish),
    active: true,
  },
  {
    key: 'zh',
    name: i18n.t(l.chinese),
    label: i18n.t(l.chinese),
    active: true,
  },
  // { // Task: TROVE-1292
  //   key: 'fr',
  //   name: i18n.t(l.french),
  //   label: i18n.t(l.french),
  //   active: true,
  // },
  // {
  //   key: 'ar',
  //   name: i18n.t(l.arabic),
  //   label: i18n.t(l.arabic),
  //   active: true,
  // },
]
