export const UPDATE_WELL_DATA = 'UPDATE_WELL_DATA'
export const UPDATE_WELL_SELECTED_DATA = 'UPDATE_WELL_SELECTED_DATA'
export const UPDATE_SEISMIC_DATA = 'UPDATE_SEISMIC_DATA'
export const UPDATE_SEISMIC_SELECTED_DATA = 'UPDATE_SEISMIC_SELECTED_DATA'
